<!DOCTYPE html>
<html>
    <head>

        <meta charset="UTF-8">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="description" content="ExtJSのコンポーネントテスト会場です">
        <title>ComponentTest</title>

        <link href="/resources/favicon.ico" rel="shortcut icon" />

        <link href="/resources/js/extjs/4.1.1/resources/css/ext-all.css" rel="stylesheet" />
        <link href="/resources/css/main.css" rel="stylesheet" />

        <script type="text/javascript" src="/resources/js/extjs/4.1.1/ext-all.js"></script>
        <script type="text/javascript" src="/resources/js/extjs/4.1.1/locale/ext-lang-ja.js"></script>

        <script type="text/javascript">
            Ext.ns('ASC');
            ASC = {};
        </script>

        <script type="text/javascript" src="/resources/js/asc/locale/asc-locale-ja.js"></script>
        <script type="text/javascript" src="/resources/js/asc/API.js"></script>        
        <script type="text/javascript" src="/src/app/Events.js"></script>
        <script type="text/javascript" src="/src/app/Controllers.js"></script>

        <?php echo '<script type="text/javascript" src="'.$this->path.'"></script>' ?>
    </head>
    <body>
        <h1><?php echo $this->cls ?> - <?php echo 'Asc' ?></h1>
        <p>
            <a href="/test">return to index</a>
        </p>

        <div id="render-component" style="padding: 25px;"></div>
    </body>
</html>
