<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="description" content="<?php echo $this->layout()->description ?>">
        <title><?php echo $this->layout()->title ?></title>

        <link href="/resources/favicon.ico" rel="shortcut icon" />

        <link href="/resources/css/bootstrap.min.css" rel="stylesheet" />
        <link href="/resources/css/bootstrap-responsive.min.css" rel="stylesheet" />
        <link href="/resources/css/error.css" rel="stylesheet" />

        <script type="text/javascript" src="/resources/js/jquery/1.8.2/jquery.min.js"></script>
        <script type="text/javascript" src="/resources/js/bootstrap.min.js"></script>
    </head>
    <body>

        <?php echo $this->layout()->content ?>
        
    </body>
</html>
